### ISSUE TITLE
Authentication failure?

### ISSUE THREAD

**Issue by jonathandewhurst** [bdwilson/wyzevac-api#1]
Builds and Runs fine. Can get to web root that shows "/api/[device]/[clean|charge|edge|spot|stop|playsound]",  but http://my.ip.address:59354/api/list results in a 500 error. I removed 2FA from my account. and have confirmed the username and password, but I can't determine where the failure is occurring or how to determine the cause of this behavior..

` * Serving Flask app 'wyzevac_flask' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.3:59354/ (Press CTRL+C to quit)
192.168.0.50 - - [18/Dec/2021 22:21:26] "GET / HTTP/1.1" 200 -
[2021-12-18 22:21:38,640] ERROR in app: Exception on /api/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/code/wyzevac-api/wyzevac_flask.py", line 118, in api3
    val = sendCommand("1","list",0)
  File "/code/wyzevac-api/wyzevac_flask.py", line 62, in sendCommand
    client = Client(config['user'],config['pass'])
  File "/usr/local/lib/python3.9/site-packages/wyze_sdk/api/client.py", line 81, in __init__
    self.login()
  File "/usr/local/lib/python3.9/site-packages/wyze_sdk/api/client.py", line 162, in login
    self._update_session(access_token=response["access_token"], refresh_token=response["refresh_token"], user_id=response["user_id"])
TypeError: 'NoneType' object is not subscriptable
192.168.0.50 - - [18/Dec/2021 22:21:38] "GET /api/list HTTP/1.1" 500 -`

**Comment by bdwilson** [comment]
Can you go into the container and see if your password looks correct in there?  The only thing I can think of might be that your password has a character in it that this doesn't like.  I think you could also create another user and share the vac with that user if you want to try an account with a less-complex password. 

$ docker exec -it wyzevac-api /bin/bash
root@98f355c8f356:/code# more /code/wyzevac-api/wyzevac_flask.py

**Comment by jonathandewhurst** [comment]
Thanks for replying. Good suggestion to investigate. I had a randomly generated password with non-alphanumeric characters. I changed the password to alphanumeric 16 characters. It shows the correct password in the container after rebuilding. Still failed. I shared the device with a family member, created another account, removed the container, rebuilt with the new account information. New build show the correct username/password. I also made sure by adding it to the dockerfile instead of passing it in the build command. Same behavior. Any other suggestions? This is a new model 200S, no other devices on the account.

**Comment by bdwilson** [comment]
I'm using the https://pypi.org/project/wyze-sdk/ library, so it may be something related to that. Unfortunately, that library hasn't been updated in a few months, and the current updates broke something for me, so I'm running an older version.
